# Generated by Django 2.2.5 on 2019-09-27 12:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('apelido', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
            ],
            managers=[
                ('objectos', django.db.models.manager.Manager()),
            ],
        ),
    ]
