# Generated by Django 2.2.5 on 2019-09-27 20:38

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('eteam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            managers=[
                ('objectos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cargo',
            field=models.CharField(choices=[('E', 'Estagiário'), ('P', 'Programador'), ('S', 'Secretário')], max_length=1),
        ),
    ]
