# Generated by Django 2.2.5 on 2019-09-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eteam', '0002_auto_20190927_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='equipa',
            field=models.ManyToManyField(to='eteam.Equipa'),
        ),
    ]
